#!/bin/bash
yum -y install gcc pam-devel zlib-devel
mv /usr/bin/openssl /usr/bin/openssl_old
mv /usr/lib64/openssl /usr/lib64/openssl_old
rpm -e --nodeps `rpm -qa |grep openssl`
tar xf /tools/openssl-1.0.2h.tar.gz&&cd openssl-1.0.2h
./config --shared && make depend && make && make install
echo "/usr/local/ssl/lib" >> /etc/ld.so.conf
ldconfig -v
echo 'export PATH=$PATH:/usr/local/ssl/bin' >>/etc/profile.d/openssh.sh
./etc/profile.d/openssh.sh
mv /etc/ssh /etc/ssh_old
rpm -e --nodeps `rpm -qa |grep openssh`
tar xf /tools/openssh-7.2p2.tar.gz
cd /tools/openssh-7.2p2
./configure  --sysconfdir=/etc/ssh --with-pam --with-zlib--without-zlib-version-check --with-ssl-dir --with-md5-passwords --mandir=/usr/share/man
make && make install
cp /tools/openssh-7.2p2/contrib/redhat/sshd.init /etc/init.d/sshd
sed -i s@SSHD=/usr/sbin/sshd@SSHD=/usr/local/sbin/sshd@g /etc/init.d/sshd
chkconfig --add sshd
chkconfig sshd on
  
